  - name: "Execute IP Check"
    command: ip a
    register: command_output
  - debug : var=command_output

  - name: Afficher le contenu de /etc/hosts
    command: cat /etc/hosts
    register: hosts_content

  - name: Afficher le contenu du fichier hosts
    debug:
      var: hosts_content.stdout_lines

#- name: Exécuter le script pour modifier /etc/hosts
#  ansible.builtin.raw: /home/oliver/modify_hosts.sh


