#- name: Définir l'adresse IP statique
#  community.general.netplan:
#    render: true
#    network:
#      version: 2
#      ethernets:
#        eth0:   # Adapter en fonction de l'interface réseau cible
#        addresses:
#          - 192.168.1.10/24  # Adresse IP statique avec son masque de sous-réseau
#        gateway4: 192.168.1.1  # Passerelle par défaut
#        nameservers:
#          addresses:
#            - 8.8.8.8  # Serveur DNS (Exemple: Google DNS)
#            - 8.8.4.4
